name: workflow.yml

on:
  push:
    branches:
      - main

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/orv-image -f docker/Dockerfile docker/

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/orv-image

